### ISSUE TITLE
与PolyLib冲突

### ISSUE THREAD

**Issue by biantwin** [StarCarefree/OpenLink#28]
### 检查项

- [X] 我确认此问题在模组最新版中仍然存在
- [ ] 我确认我是AI
- [X] 我确认在Issues列表中并无其他人已经提出过与此问题相同或相似的问题

### 模组版本

0.1.1

### 加载器及版本

Forge 40.2.10

### 遇到的问题

开启游戏时遇到模组冲突

### 期望的结果

解决问题

### 如何重现此问题

每次启动时都会出现

### 可能造成问题的原因

与PolyLib冲突

### 电脑系统环境

Win11

**Comment by zirran** [comment]
测试群中已发布适配版本
